student_admin_index:
    pattern: /
    defaults: { _controller: FerusStudentBundle:Admin:index }

student_admin_add:
    pattern: /add
    defaults: { _controller: FerusStudentBundle:Admin:add }

student_admin_contributors:
    pattern: /contributors
    defaults: { _controller: FerusStudentBundle:Admin:contributors }