student_admin_index:
    pattern: /
    defaults: { _controller: FerusStudentBundle:Admin:index }

student_admin_add:
    pattern: /add
    defaults: { _controller: FerusStudentBundle:Admin:add }

student_admin_import:
    pattern: /import
    defaults: { _controller: FerusStudentBundle:Admin:import }
    requirements:
        _method:  POST

student_admin_edit:
    pattern: /{id}/edit
    defaults: { _controller: FerusStudentBundle:Admin:edit }

student_admin_remove:
    pattern: /{id}/remove
    defaults: { _controller: FerusStudentBundle:Admin:remove }

student_admin_contributors:
    pattern: /contributors
    defaults: { _controller: FerusStudentBundle:Admin:contributors }

student_admin_contributors_search:
    pattern: /contributors/search
    defaults: { _controller: FerusStudentBundle:Admin:searchContributors }

student_admin_contributor_save:
    pattern: /{id}/setIsContributor/{value}
    defaults: { _controller: FerusStudentBundle:Admin:saveContributor }