Ferus\TransactionBundle\Entity\Transaction:
    type: entity
    table: ferus_transaction
    repositoryClass: Ferus\TransactionBundle\Repository\TransactionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: decimal
            scale: 2
            nullable: false

        completedAt:
            column: completed_at
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create

        cause:
            type: string
            length: 255
            nullable: false

    manyToOne:
        issuer:
            targetEntity: Ferus\AccountBundle\Entity\Account
            inversedBy: issuedTransactions
            fetch: EAGER
            cascade:
                - persist

        receiver:
            targetEntity: Ferus\AccountBundle\Entity\Account
            inversedBy: receivedTransactions
            fetch: EAGER
            cascade:
                - persist

        representative:
            targetEntity: Ferus\UserBundle\Entity\User
            fetch: EAGER
            gedmo:
                blameable:
                    on: create

    lifecycleCallbacks: {}
