parameters:
#    ferus_event.example.class: Ferus\EventBundle\Example

services:
    ferus_event.form.type.ticket:
        class: Ferus\EventBundle\Form\Type\TicketType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: ticket }

    ferus.csv_generator:
        class: Ferus\EventBundle\Services\CsvGenerator
        arguments:
            - @doctrine.orm.entity_manager