parameters:
#    ferus_event.example.class: Ferus\EventBundle\Example

services:
#    ferus_event.example:
#        class: %ferus_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
