Ferus\MailBundle\Entity\Auth:
    type: entity
    table: ferus_auth
    repositoryClass: Ferus\MailBundle\Repository\AuthRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        messageUid:
            type: string
            length: 255
            column: message_uid

        customFields:
            type: array
            column: custom_fields

        status:
            type: string
            length: 10

        firstWaveStatus:
            type: integer
            column: first_wave_status

        secondWaveStatus:
            type: integer
            column: second_wave_status

    manyToOne:
        template:
            targetEntity: Ferus\MailBundle\Entity\Template

    oneToMany:
        responses:
            targetEntity: Ferus\MailBundle\Entity\Response
            mappedBy: auth

    lifecycleCallbacks: {  }
