event_admin_index:
    pattern: /
    defaults: { _controller: FerusEventBundle:Admin:index }

event_admin_add:
    pattern: /add
    defaults: { _controller: FerusEventBundle:Admin:add }

event_admin_edit:
    pattern: /{id}/edit
    defaults: { _controller: FerusEventBundle:Admin:edit }

event_admin_remove:
    pattern: /{id}/remove
    defaults: { _controller: FerusEventBundle:Admin:remove }

event_admin_participants:
    pattern: /{id}/participants
    defaults: { _controller: FerusEventBundle:Admin:participants }

event_admin_money:
    pattern: /{id}/money
    defaults: { _controller: FerusEventBundle:Admin:money }

event_admin_payment_details:
    pattern: /{id}/participants/{email}
    defaults: { _controller: FerusEventBundle:Admin:details }

event_admin_payment_remove_from:
    pattern: /{id}/participants/{email}/remove
    defaults: { _controller: FerusEventBundle:Admin:removeFrom }

event_admin_payment_remove:
    pattern: /remove-payment/{id}
    defaults: { _controller: FerusEventBundle:Admin:removePayment }