Ferus\AccountBundle\Entity\Account:
    type: entity
    table: ferus_account
    repositoryClass: Ferus\AccountBundle\Repository\AccountRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        balance:
            type: decimal
            nullable: false
            scale: 2

        deletedAt:
            column: deleted_at
            type: date
            nullable: true

    oneToOne:
        student:
            targetEntity: Ferus\StudentBundle\Entity\Student
            inversedBy: account
            joinColumn:
                nullable: false
            fetch: EAGER

    oneToMany:
        issuedTransactions:
            targetEntity: Ferus\TransactionBundle\Entity\Transaction
            mappedBy: issuer

        receivedTransactions:
            targetEntity: Ferus\TransactionBundle\Entity\Transaction
            mappedBy: receiver
