Ferus\AccountBundle\Entity\Account:
    type: entity
    table: ferus_account
    repositoryClass: Ferus\AccountBundle\Repository\AccountRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        balance:
            type: decimal
            nullable: false
            scale: 2

    oneToOne:
        student:
            targetEntity: Ferus\StudentBundle\Entity\Student
            inversedBy: account
            joinColumn:
                nullable: false
            fetch: EAGER

    oneToMany:
        issuedTransactions:
            targetEntity: Ferus\TransactionBundle\Entity\Transaction
            mappedBy: issuer

        receivedTransactions:
            targetEntity: Ferus\TransactionBundle\Entity\Transaction
            mappedBy: receiver
