ferus_user_bundle_admin:
    resource: routing/admin.yml
    prefix: /admin/users

user_statement:
    path: /statement
    defaults:
        _controller: FerusUserBundle:Public:statement

user_transfer:
    path: /transfer
    defaults:
        _controller: FerusUserBundle:Public:transfer