parameters:
#    ferus_user.example.class: Ferus\UserBundle\Example

services:
#    ferus_user.example:
#        class: %ferus_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ferus_user.security.user_provider:
        class     : Ferus\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments : ['@fos_user.user_manager', '@doctrine.orm.entity_manager', '@validator', { google: google_id }]
