Ferus\EventBundle\Entity\Event:
    type: entity
    table: ferus_event
    repositoryClass: Ferus\EventBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'

        date:
            type: datetime

        maxTickets:
            column: max_tickets
            type: integer

        askForCars:
            column: ask_for_column
            type: boolean

        price:
            type: decimal
            scale: 2

        priceNonContributor:
            type: decimal
            column: price_non_contributor
            scale: 2

        deposit:
            type: decimal
            scale: 2

        depositByCheck:
            type: boolean

    oneToMany:

        carRequests:
            targetEntity: Ferus\EventBundle\Entity\CarRequest
            mappedBy: event
            cascade:
                - remove

        participations:
            targetEntity: Ferus\EventBundle\Entity\Participation
            mappedBy: event
            cascade:
                - remove

        options:
            targetEntity: Ferus\EventBundle\Entity\EventOption
            mappedBy: event
            cascade:
                - remove
                - persist

        extraFields:
            column: extra_field
            targetEntity: Ferus\EventBundle\Entity\ExtraField
            mappedBy: event
            cascade:
                - remove
                - persist

    lifecycleCallbacks: {  }
