Ferus\EventBundle\Entity\Event:
    type: entity
    table: ferus_event
    repositoryClass: Ferus\EventBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'

        date:
            type: datetime

        maxTickets:
            column: max_tickets
            type: integer

        askForCars:
            column: ask_for_column
            type: boolean

    oneToMany:
        tickets:
            targetEntity: Ferus\EventBundle\Entity\Ticket
            mappedBy: event
            cascade:
                - persist
                - remove

        payments:
            targetEntity: Ferus\EventBundle\Entity\Payment
            mappedBy: event

        carRequests:
            targetEntity: Ferus\EventBundle\Entity\CarRequest
            mappedBy: event
            cascade:
                - remove

    lifecycleCallbacks: {  }
