Ferus\EventBundle\Entity\Payment:
    type: entity
    table: ferus_payment
    repositoryClass: Ferus\EventBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: '100'
            column: first_name

        lastName:
            type: string
            length: '100'
            column: last_name

        email:
            type: string
            length: 255

        studentId:
            type: integer
            column: student_id
            nullable: true

        amount:
            type: integer

        method:
            type: string
            length: '100'

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

    manyToOne:
        event:
            targetEntity: Ferus\EventBundle\Entity\Event
            inversedBy: payments

        ticket:
            targetEntity: Ferus\EventBundle\Entity\Ticket
            inversedBy: payments

    lifecycleCallbacks: {  }
