ferus_transaction_bundle:
    resource: "@FerusTransactionBundle/Resources/config/routing.yml"
    prefix:   /

ferus_account_bundle:
    resource: "@FerusAccountBundle/Resources/config/routing.yml"
    prefix:   /

ferus_student_bundle:
    resource: "@FerusStudentBundle/Resources/config/routing.yml"
    prefix: /

ferus_admin_index:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::admin.html.twig'

# Vendors

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc