ferus_event_bundle:
    resource: "@FerusEventBundle/Resources/config/routing.yml"
    prefix:   /

ferus_seller_bundle:
    resource: "@FerusSellerBundle/Resources/config/routing.yml"
    prefix:   /

ferus_transaction_bundle:
    resource: "@FerusTransactionBundle/Resources/config/routing.yml"
    prefix:   /

ferus_account_bundle:
    resource: "@FerusAccountBundle/Resources/config/routing.yml"
    prefix:   /

ferus_student_bundle:
    resource: "@FerusStudentBundle/Resources/config/routing.yml"
    prefix: /

ferus_user_bundle:
    resource: "@FerusUserBundle/Resources/config/routing.yml"
    prefix: /

ferus_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::homepage.html.twig'

ferus_other_operations:
    path: /other-operations
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::other-operations.html.twig'

ferus_admin_index:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::admin.html.twig'

# Vendors

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc