security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SELLER:            ROLE_USER
        ROLE_ADMIN:             ROLE_USER
        ROLE_USER_ADMIN:        ROLE_ADMIN
        ROLE_STUDENT_ADMIN:     ROLE_ADMIN
        ROLE_SELLER_ADMIN:      ROLE_ADMIN
        ROLE_ACCOUNT_ADMIN:     ROLE_ADMIN
        ROLE_TRANSACTION_ADMIN: ROLE_ACCOUNT_ADMIN
        ROLE_WITHDRAWAL_ADMIN:  ROLE_TRANSACTION_ADMIN
        ROLE_SUPER_ADMIN:       [ROLE_WITHDRAWAL_ADMIN, ROLE_SELLER_ADMIN, ROLE_STUDENT_ADMIN, ROLE_USER_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/edit, role: ROLE_ADMIN }
        - { path: ^/admin/users, role: ROLE_USER_ADMIN }
        - { path: ^/admin/students, role: ROLE_STUDENT_ADMIN }
        - { path: ^/admin/sellers, role: ROLE_SELLER_ADMIN }
        - { path: ^/admin/accounts, role: ROLE_ACCOUNT_ADMIN }
        - { path: ^/admin/transactions/withdrawal, role: ROLE_WITHDRAWAL_ADMIN }
        - { path: ^/admin/transactions, role: ROLE_TRANSACTION_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
