parameters:
#    ferus_student.example.class: Ferus\StudentBundle\Example

services:
#    ferus_student.example:
#        class: %ferus_student.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
