ferus_mail_bundle_authority_admin:
    resource: routing/authority.yml
    prefix: /admin/authorizations/authorities

ferus_mail_bundle_template_admin:
    resource: routing/template.yml
    prefix: /admin/authorizations/templates

ferus_mail_bundle_auth_admin:
    resource: routing/auth.yml
    prefix: /admin/authorizations