parameters:
#    ferus_mail.example.class: Ferus\MailBundle\Example

services:
    ferus_mail.form.type.tag:
        class: Ferus\MailBundle\Form\Type\TagType
        tags:
            - { name: form.type, alias: tag }
