Ferus\UserBundle\Entity\User:
    type: entity
    table: ferus_user
    repositoryClass: Ferus\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        google_id:
            type: string
            length: 255
            nullable: true

        google_access_token:
            type: string
            length: 255
            nullable: true

    oneToOne:
        account:
            targetEntity: Ferus\AccountBundle\Entity\Account
            inversedBy: user
