Ferus\UserBundle\Entity\User:
    type: entity
    table: ferus_user
    repositoryClass: Ferus\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToOne:
        account:
            targetEntity: Ferus\AccountBundle\Entity\Account
            inversedBy: user
