Ferus\SellerBundle\Entity\Seller:
    type: entity
    table: ferus_seller
    repositoryClass: Ferus\SellerBundle\Repository\SellerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
            nullable: false
            unique: true

        apiKey:
            type: string
            length: 255
            unique: true

    oneToOne:
        account:
            targetEntity: Ferus\AccountBundle\Entity\Account
            mappedBy: seller

    lifecycleCallbacks: {  }
