Ferus\SellerBundle\Entity\Store:
    type: entity
    table: ferus_store
    repositoryClass: Ferus\SellerBundle\Repository\StoreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            nullable: false

    manyToOne:
        seller:
            targetEntity: Ferus\SellerBundle\Entity\Seller
            inversedBy: stores

    oneToMany:
        products:
            targetEntity: Ferus\SellerBundle\Entity\Product
            mappedBy: store
            cascade:
                - remove

    lifecycleCallbacks: {  }
