seller_dashboard:
    pattern: /dashboard
    defaults: { _controller: FerusSellerBundle:Seller:dashboard }

seller_cash_register:
    pattern: /{salt}/cash-register
    defaults: { _controller: FerusSellerBundle:Seller:cashRegister }

seller_new_store:
    pattern: /stores/new
    defaults: { _controller: FerusSellerBundle:Seller:newStore }

seller_store:
    pattern: /stores/{id}
    defaults: { _controller: FerusSellerBundle:Seller:store }

seller_remove_store:
    pattern: /stores/{id}/remove
    defaults: { _controller: FerusSellerBundle:Seller:removeStore }

seller_new_product:
    pattern: /stores/{id}/new-product
    defaults: { _controller: FerusSellerBundle:Seller:newProduct }

seller_remove_product:
    pattern: /products/{id}/remove
    defaults: { _controller: FerusSellerBundle:Seller:removeProduct }

seller_edit_product:
    pattern: /products/{id}/edit
    defaults: { _controller: FerusSellerBundle:Seller:editProduct }