parameters:
#    ferus_account.example.class: Ferus\AccountBundle\Example

services:
    ferus_account.form.type.euro:
        class: Ferus\AccountBundle\Form\Type\EuroType
        tags:
            - { name: form.type, alias: euro }

    ferus_account.form.type.barcode:
        class: Ferus\AccountBundle\Form\Type\BarcodeType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: barcode }
