parameters:
#    ferus_account.example.class: Ferus\AccountBundle\Example

services:
#    ferus_account.example:
#        class: %ferus_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
