parameters:
#    ferus_seller.example.class: Ferus\SellerBundle\Example

services:
#    ferus_seller.example:
#        class: %ferus_seller.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
