account_admin_index:
    pattern: /
    defaults: { _controller: FerusAccountBundle:Admin:index }

account_admin_add:
    pattern: /add
    defaults: { _controller: FerusAccountBundle:Admin:add }

account_admin_view:
    pattern: /{student}/view
    defaults: { _controller: FerusAccountBundle:Admin:view }