account_admin_index:
    pattern: /
    defaults: { _controller: FerusAccountBundle:Admin:index }

account_admin_add:
    pattern: /add
    defaults: { _controller: FerusAccountBundle:Admin:add }

account_admin_view:
    pattern: /{id}
    defaults: { _controller: FerusAccountBundle:Admin:view }

account_admin_remove:
    pattern: /{id}/remove
    defaults: { _controller: FerusAccountBundle:Admin:remove }