parameters:
#    ferus_transaction.example.class: Ferus\TransactionBundle\Example

services:
#    ferus_transaction.example:
#        class: %ferus_transaction.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
