parameters:
#    ferus_transaction.example.class: Ferus\TransactionBundle\Example

services:
    ferus_transaction.transaction_core:
        class: Ferus\TransactionBundle\Transaction\TransactionCore
        arguments:
            - @doctrine.orm.entity_manager
