Ferus\StudentBundle\Entity\Student:
    type: entity
    table: ferus_student
    repositoryClass: Ferus\StudentBundle\Repository\StudentRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: NONE
    fields:
        firstName:
            column: first_name
            type: string
            length: '50'
            nullable: false

        lastName:
            column: last_name
            type: string
            length: '50'
            nullable: false

        isContributor:
            column: is_contributor
            type: boolean
            nullable: false

        email:
            type: string
            length: 255
            nullable: false

        login:
            type: string
            length: 8
            nullable: false

        class:
            type: string
            length: 10
            nullable: false

        deletedAt:
            column: deleted_at
            type: date
            nullable: true

    oneToOne:
        account:
            targetEntity: Ferus\AccountBundle\Entity\Account
            mappedBy: student

    lifecycleCallbacks:
        prePersist: [ generateLogin, generateEmail ]
        preUpdate: [ generateLogin, generateEmail ]
